version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - store_test_results:
          path: test-results
      - newman/newman-run:
          collection: ./Filmes.postman_collection.json
          environment: ./OMDb-API.postman_environment.json
      